#!/bin/sh
# PH database build script
# Designed from numerous contributions to the info-ph list
# Coded by Noel Hunter (noel@camelcity.com)
#
# Builds a PH Database from the input stored in the file qi.input.
# During the build, works on a copy of the database, not the working version.
# If disk space is a premium, modify the script to work on prod, not prod-new.
#
# The latest version of this script is available from:
# http://www.camelcity.com/~noel/usenet/ph-build.sh
#
echo "PH database build script started..."
#
# cd to the cso library directory.  We assume all the cso programs
# are installed here:
cd /opt/nameserv

cp util/db/prod-new.cnf prod-new.cnf
cp util/db/qi.input qi.input

#
# Determine the size for the database using the "sizedb" program
# that comes with the server.  You need perl to use sizedb, along
# with the file primes.shar.  If you don't have these, you can hard-
# code in a prime bigger than the number of indexed fields (from the
# cnf file) times the number of records in your database (qi.input):
echo "Calculating size..."
size=`./bin/sizedb prod-new.cnf qi.input`
#
# Build the database using the specifications in "prod-new.cnf", and the
# data in "qi.input"
echo "Executing credb..."
./bin/credb $size prod-new
echo "Executing maked..."
./bin/maked prod-new <qi.input
echo "Executing makei..."
./bin/makei prod-new
echo "Executing build..."
./bin/build -s prod-new
#
# Move the new database into place:
echo "Moving database into place..."
mv prod-new.bdx db/prod.bdx
mv prod-new.bnr db/prod.bnr
mv prod-new.dir db/prod.dir
mv prod-new.dov db/prod.dov
mv prod-new.idx db/prod.idx
mv prod-new.iov db/prod.iov
mv prod-new.lck db/prod.lck
mv prod-new.seq db/prod.seq
mv prod-new.cnf db/prod.cnf
#
echo "PH database build script complete."